# Tensor

- Multi Dimensional Array

## Import libraries

In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
print("Torchversion: ", torch.__version__)
print("Numpy version: ", np.__version__)
print("Pandas version: ", pd.__version__)

Torchversion:  2.9.1
Numpy version:  2.3.5
Pandas version:  2.3.3


## Create Tensor

### Initialize Tensor

In [3]:
x = torch.tensor([1,2,3,4,5,6]) # 1D Tensor (Vector)
print("Tensor x: ", x)
print("Shape of x: ", x.shape) # 6 elements
print("Datatype of x: ", x.dtype) # int64

Tensor x:  tensor([1, 2, 3, 4, 5, 6])
Shape of x:  torch.Size([6])
Datatype of x:  torch.int64


In [5]:
x = torch.tensor([[1.0, 2.0 , 3.0],[4.0,5.0,6.0]]) # 2D Tensor (Matrix)
print("Tensor x: ", x)
print("Shape of x: ", x.shape) # 2 rows, 3 columns
print("Datatype of x: ", x.dtype) # float32

Tensor x:  tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape of x:  torch.Size([2, 3])
Datatype of x:  torch.float32


In [6]:
x = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]) # 3D Tensor
print("Tensor x: ", x)
print("Shape of x: ", x.shape) # 3 matrices (batchs), 2 rows, 3 columns
print("Datatype of x: ", x.dtype) # int64

Tensor x:  tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
Shape of x:  torch.Size([3, 2, 3])
Datatype of x:  torch.int64


### Tensor from Numpy Array

In [8]:
numpy_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
torch_tensor = torch.from_numpy(numpy_array)
print("Numpy Array:\n", numpy_array)
print("Shape of Numpy Array:", numpy_array.shape)
print("Datatype of Numpy Array:", numpy_array.dtype)
print("=" * 50)
print("Converted Torch Tensor:\n", torch_tensor)
print("Shape of Torch Tensor:", torch_tensor.shape)
print("Datatype of Torch Tensor:", torch_tensor.dtype)

Numpy Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape of Numpy Array: (2, 4)
Datatype of Numpy Array: int64
Converted Torch Tensor:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Shape of Torch Tensor: torch.Size([2, 4])
Datatype of Torch Tensor: torch.int64


### Tensor from Pandas DataFrame

In [9]:
data = {'time': [1, 5, 10, 20], 'speed': [2, 50, 75, 120]}
pandas_df = pd.DataFrame(data)
torch_tensor_from_pandas = torch.from_numpy(pandas_df.values)

print("Pandas DataFrame:\n", pandas_df)
print("Pandas DataFrame dtypes:\n", pandas_df.dtypes)
print("Pandas DataFrame shape:\n", pandas_df.shape)
print("=" * 50)
print("Torch Tensor from Pandas:\n", torch_tensor_from_pandas)
print("Torch Tensor type:\n", torch_tensor_from_pandas.dtype)
print("Torch Tensor shape:\n", torch_tensor_from_pandas.shape)

Pandas DataFrame:
    time  speed
0     1      2
1     5     50
2    10     75
3    20    120
Pandas DataFrame dtypes:
 time     int64
speed    int64
dtype: object
Pandas DataFrame shape:
 (4, 2)
Torch Tensor from Pandas:
 tensor([[  1,   2],
        [  5,  50],
        [ 10,  75],
        [ 20, 120]])
Torch Tensor type:
 torch.int64
Torch Tensor shape:
 torch.Size([4, 2])


### Predifined Value (Zeros, Ones)

In [10]:
zeros = torch.zeros((3, 4))
print("Zeros Tensor:\n", zeros)
print("Shape of Zeros Tensor:", zeros.shape)
print("Datatype of Zeros Tensor:", zeros.dtype)

Zeros Tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape of Zeros Tensor: torch.Size([3, 4])
Datatype of Zeros Tensor: torch.float32


In [11]:
zeros = torch.zeros((3, 4, 5))
print("Zeros Tensor:\n", zeros)
print("Shape of Zeros Tensor:", zeros.shape)

Zeros Tensor:
 tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
Shape of Zeros Tensor: torch.Size([3, 4, 5])


In [12]:
ones = torch.ones((2, 3))
print("Ones Tensor:\n", ones)   
print("Shape of Ones Tensor:", ones.shape)

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Shape of Ones Tensor: torch.Size([2, 3])


In [13]:
ones = torch.ones((3, 1, 4))
print("Ones Tensor:\n", ones)

Ones Tensor:
 tensor([[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]])


### Random Values

In [14]:
random = torch.rand((2, 3))
print("Random Tensor:\n", random)

Random Tensor:
 tensor([[0.5981, 0.6813, 0.9035],
        [0.3847, 0.3743, 0.6265]])


In [15]:
random_tensor = torch.rand((2, 3, 4))
print("Random 3D Tensor:\n", random_tensor)

Random 3D Tensor:
 tensor([[[0.8587, 0.6059, 0.9283, 0.0049],
         [0.5202, 0.7497, 0.9861, 0.7509],
         [0.8628, 0.5730, 0.4182, 0.4270]],

        [[0.7479, 0.2428, 0.2757, 0.2095],
         [0.6727, 0.6205, 0.0065, 0.1654],
         [0.6836, 0.2885, 0.7499, 0.2974]]])


### From a Sequence (torch.arange())

In [16]:
range_tensor = torch.arange(0, 10, step=1)
print("Range Tensor:\n", range_tensor) # 1D Tensor from 0 to 9

Range Tensor:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
even_tensor = torch.arange(0, 10, step=2)
print("Even Tensor:", even_tensor) # 1D Tensor from 0 to 8 with step size 2

Range Tensor: tensor([0, 2, 4, 6, 8])


In [19]:
odd_tensor = torch.arange(1, 10, step=2)
print("Odd Tensor:", odd_tensor) # 1D Tensor from 1 to 9 with step size 2

Odd Tensor: tensor([1, 3, 5, 7, 9])


In [22]:
decrease_tensor = torch.arange(10, 0, step=-1)
print("Decrease Tensor:", decrease_tensor) # 1D Tensor from 10 to 1

Decrease Tensor: tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


In [23]:
decrease_tensor = torch.arange(10, -1, step=-1)
print("Decrease Tensor:", decrease_tensor) # 1D Tensor from 10 to 0

Decrease Tensor: tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])


## Reshaping and Manipulating

In [24]:
# A 2D Tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor x:\n", x)
print("Original Tensor Shape:\n", x.shape)

Original Tensor x:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Original Tensor Shape:
 torch.Size([2, 3])


### Changing a Tensor's Dimension

#### Add Dimension

In [34]:
print("Original Tensor:\n", x)
print("\nOriginal Tensor shape:\n", x.shape)
print("-"*50)

# Add dimension
expanded_tensor = x.unsqueeze(0) # Add dimension at index 0, shape is [1,2,3]
print("Expanded Tensor:\n", expanded_tensor)
print("Added dimension at index 0 (First position)")
print("\nExpanded Tensor shape:\n", expanded_tensor.shape)

Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Original Tensor shape:
 torch.Size([2, 3])
--------------------------------------------------
Expanded Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6]]])
Added dimension at index 0 (First position)

Expanded Tensor shape:
 torch.Size([1, 2, 3])


In [30]:
expanded_tensor = x.unsqueeze(1) # Add dimension at index 1, shape is [2,1,3]
print("Expanded Tensor:\n", expanded_tensor)
print("Added dimension at index 1 (Second position)")
print("\nExpanded Tensor shape:\n", expanded_tensor.shape)

Expanded Tensor:
 tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
Added dimension at index 1 (Second position)

Expanded Tensor shape:
 torch.Size([2, 1, 3])


In [32]:
expanded_tensor = x.unsqueeze(2) # Add dimension at index 2, shape is [2,3,1]
print("Expanded Tensor:\n", expanded_tensor)
print("Added dimension at index 2 (Third position)")
print("\nExpanded Tensor shape:\n", expanded_tensor.shape)

Expanded Tensor:
 tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])
Added dimension at index 2 (Third position)

Expanded Tensor shape:
 torch.Size([2, 3, 1])


#### Remove Dimension

In [35]:
print("Expanded Tensor:\n", expanded_tensor)
print("\nExpanded Tensor shape:\n", expanded_tensor.shape)
print("-"*50)

# Remove Dimension
squeezed_tensor = expanded_tensor.squeeze(0) # Remove dimension at index 0, shape is [2,3]

print("Squeezed Tensor:\n", squeezed_tensor)
print("\nSqueezed Tensor shape:\n", squeezed_tensor.shape)

Expanded Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Expanded Tensor shape:
 torch.Size([1, 2, 3])
--------------------------------------------------
Squeezed Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Squeezed Tensor shape:
 torch.Size([2, 3])


### Restucturing and Reshaping

In [36]:
print("Original Tensor:\n", x)
print("\nOriginal Tensor shape:\n", x.shape)
print("-"*50)

# Reshape
reshaped_tensor = x.reshape(3,2)

print("Reshaped Tensor:\n", reshaped_tensor)
print("\nReshaped Tensor shape:\n", reshaped_tensor.shape)

Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Original Tensor shape:
 torch.Size([2, 3])
--------------------------------------------------
Reshaped Tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Reshaped Tensor shape:
 torch.Size([3, 2])


In [37]:
# Create a 2x3x4 tensor
original_tensor = torch.rand(2, 3, 4)
print("Original Tensor (2x3x4):\n", original_tensor)
print("Original Tensor shape:", original_tensor.shape)

print("\n" + "-"*50 + "\n")

# Reshape the tensor to a 4x6 tensor
reshaped_tensor = original_tensor.reshape(4, 6)
print("Reshaped Tensor (4x6):\n", reshaped_tensor)
print("Reshaped Tensor shape:", reshaped_tensor.shape)

Original Tensor (2x3x4):
 tensor([[[0.3250, 0.0924, 0.5937, 0.3862],
         [0.5803, 0.3676, 0.8926, 0.3959],
         [0.7072, 0.1835, 0.4519, 0.3388]],

        [[0.2065, 0.8604, 0.3744, 0.4794],
         [0.6271, 0.9194, 0.9641, 0.1022],
         [0.4926, 0.1743, 0.6478, 0.3212]]])
Original Tensor shape: torch.Size([2, 3, 4])

--------------------------------------------------

Reshaped Tensor (4x6):
 tensor([[0.3250, 0.0924, 0.5937, 0.3862, 0.5803, 0.3676],
        [0.8926, 0.3959, 0.7072, 0.1835, 0.4519, 0.3388],
        [0.2065, 0.8604, 0.3744, 0.4794, 0.6271, 0.9194],
        [0.9641, 0.1022, 0.4926, 0.1743, 0.6478, 0.3212]])
Reshaped Tensor shape: torch.Size([4, 6])


### Transposing 

In [38]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Transpose
transposed_tensor = x.transpose(0, 1) # same x.T

print("TRANSPOSED TENSOR:\n\n", transposed_tensor)
print("\nTENSOR SHAPE:", transposed_tensor.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------
TRANSPOSED TENSOR:

 tensor([[1, 4],
        [2, 5],
        [3, 6]])

TENSOR SHAPE: torch.Size([3, 2])


In [39]:
tensor = torch.tensor([[[1,2,3,4],    [5,6,7,8],    [9,10,11,12]],
                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("3D Tensor:\n", tensor)
print("3D Tensor shape:\n", tensor.shape)
print("-"*50)

transposed_3D_tensor = tensor.transpose(1,2)
print("Transposed 3D Tensor:\n", transposed_3D_tensor)
print("Transposed 3D Tensor Shape: \n", transposed_3D_tensor.shape)

3D Tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
3D Tensor shape:
 torch.Size([2, 3, 4])
--------------------------------------------------
Transposed 3D Tensor:
 tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
Transposed 3D Tensor Shape: 
 torch.Size([2, 4, 3])


### Combining Tensor (Concatenate)

- All tensors must have same shape in dimenstions other than the one being concatenated

In [40]:
# Create two tensors to concatenate
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

# Concatenate along columns (dim=1)
concatenated_tensors = torch.cat((tensor_a, tensor_b), dim=1)


print("TENSOR A:\n\n", tensor_a)
print("\nTENSOR B:\n\n", tensor_b)
print("-"*45)
print("\nCONCATENATED TENSOR: (dim=1)\n\n", concatenated_tensors)
print("\n CONCATENATED TENSOR SHAPE: \n", concatenated_tensors.shape)

TENSOR A:

 tensor([[1, 2],
        [3, 4]])

TENSOR B:

 tensor([[5, 6],
        [7, 8]])
---------------------------------------------

CONCATENATED TENSOR: (dim=1)

 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

 CONCATENATED TENSOR SHAPE: 
 torch.Size([2, 4])


In [41]:
tensor_1 = torch.tensor([[[1,2,3,4],    [5,6,7,8],    [9,10,11,12]],
                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
tensor_2 = torch.tensor([[[25,26,27,28],[29,30,31,32],[33,34,35,36]],
                         [[37,38,39,40],[41,42,43,44],[45,46,47,48]]])

concatenated_tensors = torch.cat((tensor_1, tensor_2), dim=0)

print("TENSOR 1:\n\n", tensor_1)
print("\nTENSOR 2:\n\n", tensor_2)
print("\nTENSOR SHAPE:\n", tensor_1.shape)
print("-"*45)

print("\nCONCATENATED TENSOR: (dim=0)\n\n", concatenated_tensors)
print("\n CONCATENATED TENSOR SHAPE: \n", concatenated_tensors.shape)

TENSOR 1:

 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

TENSOR 2:

 tensor([[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])

TENSOR SHAPE:
 torch.Size([2, 3, 4])
---------------------------------------------

CONCATENATED TENSOR: (dim=0)

 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]],

        [[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])

 CONCATENATED TENSOR SHAPE: 
 torch.Size([4, 3, 4])


### Indexing and Slicing

#### Accesing Elements

In [43]:
x = torch.tensor([
    [1,2, 3, 4 ],
    [5,6, 7, 8 ],
    [9,10,11,12]
])
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get a single element at row 1 (second row), column 2 (third column)
single_element_tensor = x[1, 2] # tensor(7) index=1 means 2nd row,

print("\nINDEXING SINGLE ELEMENT AT [1, 2]:", single_element_tensor)
print("-" * 55)

# Get the entire second row (index 1)
second_row = x[1]

print("\nINDEXING ENTIRE ROW [1]:", second_row)
print("-" * 55)

# Last row
last_row = x[-1]

print("\nINDEXING ENTIRE LAST ROW ([-1]):", last_row, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2]: tensor(7)
-------------------------------------------------------

INDEXING ENTIRE ROW [1]: tensor([5, 6, 7, 8])
-------------------------------------------------------

INDEXING ENTIRE LAST ROW ([-1]): tensor([ 9, 10, 11, 12]) 



#### Columns

In [44]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

first_col = x[:, 0]
print("FIRST COLUMN: \n", first_col)

last_col = x[:, -1]
print("LAST COLUMN: \n", last_col)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
FIRST COLUMN: 
 tensor([1, 5, 9])
LAST COLUMN: 
 tensor([ 4,  8, 12])


In [48]:
# 3D Tensor Indexing
X = torch.tensor([[[1,2,3,4],    [5,6,7,8],    [9,10,11,12]],
                  [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("ORIGINAL TENSOR:\n\n", X)
print("-" * 55)

single_element_tensor = X[1, 2, 3] # tensor(24)
print("\nINDEXING SINGLE ELEMENT AT [1, 2, 3]:", single_element_tensor)

second_row = X[:, 1]
print("\nINDEXING ENTIRE ROW [:, 1]:", second_row)

last_row = X[1, -1]
print("\nINDEXING ENTIRE LAST ROW [1, -1]:", last_row, "\n")

first_col = X[:, :, 0]
print("FIRST COLUMN: \n", first_col)

last_col = X[:, :, -1]
print("LAST COLUMN: \n", last_col)


ORIGINAL TENSOR:

 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2, 3]: tensor(24)

INDEXING ENTIRE ROW [:, 1]: tensor([[ 5,  6,  7,  8],
        [17, 18, 19, 20]])

INDEXING ENTIRE LAST ROW [1, -1]: tensor([21, 22, 23, 24]) 

FIRST COLUMN: 
 tensor([[ 1,  5,  9],
        [13, 17, 21]])
LAST COLUMN: 
 tensor([[ 4,  8, 12],
        [16, 20, 24]])


In [59]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Every odd column
every_other_col = x[:, ::2]

print("\nEVERY ODD COLUMN ([:, ::2]):\n\n", every_other_col)
print("-" * 55)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

EVERY ODD COLUMN ([:, ::2]):

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
-------------------------------------------------------


In [60]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Every even column (columns at index 1, 3, etc.)
every_even_col = x[:, 1::2]

print("\nEVERY EVEN COLUMN ([:, 1::2]):\n\n", every_even_col)
print("-" * 55)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

EVERY EVEN COLUMN ([:, 1::2]):

 tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])
-------------------------------------------------------


#### Rows

In [51]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get the first two rows
first_two_rows = x[:2] # [start:end:step]

print("Slicing first two rows [0:2]:\n", first_two_rows)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
Slicing first two rows [0:2]:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


#### Every Odd Row

In [47]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Every odd row (rows at index 0, 2, etc.)
every_odd_row = x[::2, :]

print("\nEVERY ODD ROW ([::2, :]):\n\n", every_odd_row)
print("-" * 55)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

EVERY ODD ROW ([::2, :]):

 tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])
-------------------------------------------------------


#### Every Even Row

In [54]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Every even row (rows at index 1, 3, etc.)
every_even_row = x[1::2, :]

print("\nEVERY EVEN ROW ([1::2, :]):\n\n", every_even_row)
print("-" * 55)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

EVERY EVEN ROW ([1::2, :]):

 tensor([[5, 6, 7, 8]])
-------------------------------------------------------


In [58]:
print("ORIGINAL TENSOR:\n\n", X)
print("-" * 50)

# Every odd row (rows at index 0, 2, etc.)
every_odd_row = X[:, ::2, :]

print("\nEVERY ODD ROW ([::2, :]):\n\n", every_odd_row)
print("-" * 50)

ORIGINAL TENSOR:

 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
--------------------------------------------------

EVERY ODD ROW ([::2, :]):

 tensor([[[ 1,  2,  3,  4],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [21, 22, 23, 24]]])
--------------------------------------------------


### Combining Indexing and Slicing

In [61]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Combining slicing and indexing (First two rows, last two columns)
combined = x[0:2, 2:]

print("\nFIRST TWO ROWS, LAST TWO COLS ([0:2, 2:]):\n\n", combined, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

FIRST TWO ROWS, LAST TWO COLS ([0:2, 2:]):

 tensor([[3, 4],
        [7, 8]]) 



### Extracting the Value from Tensor

In [62]:
print("SINGLE-ELEMENT TENSOR:", single_element_tensor)
print("-" * 45)

# Extract the value from a single-element tensor as a standard Python number
value = single_element_tensor.item()

print("\n.item() PYTHON NUMBER EXTRACTED:", value)
print("TYPE:", type(value))

SINGLE-ELEMENT TENSOR: tensor(24)
---------------------------------------------

.item() PYTHON NUMBER EXTRACTED: 24
TYPE: <class 'int'>


In [63]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

single_element_tensor = x[1, 2] # tensor(7)

print("SINGLE-ELEMENT TENSOR:", single_element_tensor)
print("-" * 45)

value = single_element_tensor.item()

print("\n.item() PYTHON NUMBER EXTRACTED:", value)
print("TYPE:", type(value))

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
SINGLE-ELEMENT TENSOR: tensor(7)
---------------------------------------------

.item() PYTHON NUMBER EXTRACTED: 7
TYPE: <class 'int'>


In [ ]:
X = torch.tensor([[[1,2,3,4],    [5,6,7,8],    [9,10,11,12]],
                  [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("ORIGINAL TENSOR:\n\n", X)
print("-" * 55)

single_element_tensor = X[1, 2, 3] # tensor(24)

print("SINGLE-ELEMENT TENSOR:", single_element_tensor)
print("-" * 45)

# Extract the value from a single-element tensor as a standard Python number
value = single_element_tensor.item()

print("\n.item() PYTHON NUMBER EXTRACTED:", value)
print("TYPE:", type(value))

### Boolean Masking

In [64]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Boolean indexing using logical comparisons
mask = x > 6

print("MASK (VALUES > 6):\n\n", mask, "\n")

# Applying Boolean masking
mask_applied = x[mask]

print("VALUES AFTER APPLYING MASK:", mask_applied, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MASK (VALUES > 6):

 tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]]) 

VALUES AFTER APPLYING MASK: tensor([ 7,  8,  9, 10, 11, 12]) 



In [65]:
X = torch.tensor([[[1,2,3,4],    [5,6,7,8],    [9,10,11,12]],
                  [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("ORIGINAL TENSOR:\n\n", X)
print("-" * 55)

mask = X > 10

print("MASK (VALUES > 10):\n\n", mask, "\n")

mask_applied = X[mask]

print("Values after applying mask: ", mask_applied)

ORIGINAL TENSOR:

 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
-------------------------------------------------------
MASK (VALUES > 6):

 tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False,  True,  True]],

        [[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]]) 

Values after applying mask:  tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])


In [67]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

masking = x % 2 == 0  # Mask for even numbers
print("MASK FOR EVEN NUMBERS:\n\n", masking, "\n")
masked_tensor = x[masking]
print("EVEN NUMBERS AFTER APPLYING MASK:\n\n", masked_tensor)


ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MASK FOR EVEN NUMBERS:

 tensor([[False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True]]) 

EVEN NUMBERS AFTER APPLYING MASK:

 tensor([ 2,  4,  6,  8, 10, 12])


In [68]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)
masking = x % 2 != 0  # Mask for odd numbers
print("MASK FOR ODD NUMBERS:\n\n", masking, "\n")
masked_tensor = x[masking]
print("ODD NUMBERS AFTER APPLYING MASK:\n\n", masked_tensor) 

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MASK FOR ODD NUMBERS:

 tensor([[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]]) 

ODD NUMBERS AFTER APPLYING MASK:

 tensor([ 1,  3,  5,  7,  9, 11])


### Causal Masking

In [70]:
# Causal Masking - Create a mask where each position can only attend to previous positions
seq_len = 4
causal_mask = torch.tril(torch.ones(seq_len, seq_len)) == 1

print("CAUSAL MASK:\n\n", causal_mask, "\n")
print("-" * 55)

# Example: Apply causal mask to a tensor
example_tensor = torch.arange(16).reshape(4, 4).float()  # Convert to float for -inf masking
print("ORIGINAL TENSOR:\n\n", example_tensor, "\n")
print("-" * 55)

# Mask values where causal_mask is False
masked_result = example_tensor.masked_fill(~causal_mask, float('-inf'))
print("TENSOR WITH CAUSAL MASK APPLIED:\n\n", masked_result)

CAUSAL MASK:

 tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]]) 

-------------------------------------------------------
ORIGINAL TENSOR:

 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]) 

-------------------------------------------------------
TENSOR WITH CAUSAL MASK APPLIED:

 tensor([[ 0., -inf, -inf, -inf],
        [ 4.,  5., -inf, -inf],
        [ 8.,  9., 10., -inf],
        [12., 13., 14., 15.]])


### Fancy Indexing

In [71]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get first and third rows
row_indices = torch.tensor([0, 2])

# Get second and fourth columns
col_indices = torch.tensor([1, 3])

# Gets values at (0,1), (0,3), (2,1), (2,3)
get_values = x[row_indices[:, None], col_indices]

print("\nSPECIFIC ELEMENTS USING INDICES:\n\n", get_values, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SPECIFIC ELEMENTS USING INDICES:

 tensor([[ 2,  4],
        [10, 12]]) 



## Math Operations

### Element-wise Addition

In [76]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print("TENSOR A:", a)
print("TENSOR B", b)
print("TENSOR SHAPE:\n", a.shape)
print("-" * 60)

# Element-wise addition
element_add = a + b

print("\nAFTER PERFORMING ELEMENT-WISE ADDITION:\n", element_add, "\n")
print("AFTER PERFORMING ELEMENT-WISE ADDITION SHAPE:\n ", element_add.shape)

TENSOR A: tensor([[1, 2, 3],
        [4, 5, 6]])
TENSOR B tensor([[ 7,  8,  9],
        [10, 11, 12]])
TENSOR SHAPE:
 torch.Size([2, 3])
------------------------------------------------------------

AFTER PERFORMING ELEMENT-WISE ADDITION:
 tensor([[ 8, 10, 12],
        [14, 16, 18]]) 

AFTER PERFORMING ELEMENT-WISE ADDITION SHAPE:
  torch.Size([2, 3])


### Element-wise Multiplication

In [77]:
print("TENSOR A:", a)
print("TENSOR B", b)
print("TENSOR SHAPE:\n", a.shape)
print("-" * 65)

# Element-wise multiplication
element_mul = a * b

print("\nAFTER PERFORMING ELEMENT-WISE MULTIPLICATION:\n", element_mul, "\n")
print("AFTER PERFORMING ELEMENT-WISE MULTIPLICATION SHAPE:\n ", element_mul.shape)

TENSOR A: tensor([[1, 2, 3],
        [4, 5, 6]])
TENSOR B tensor([[ 7,  8,  9],
        [10, 11, 12]])
TENSOR SHAPE:
 torch.Size([2, 3])
-----------------------------------------------------------------

AFTER PERFORMING ELEMENT-WISE MULTIPLICATION:
 tensor([[ 7, 16, 27],
        [40, 55, 72]]) 

AFTER PERFORMING ELEMENT-WISE MULTIPLICATION SHAPE:
  torch.Size([2, 3])


### Dot Product

In [81]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([7, 8, 9])
print("TENSOR A:", a)
print("TENSOR B", b)
print("TENSOR SHAPE:\n", a.shape)
print("-" * 65)

# Dot product
dot_product = torch.matmul(a, b)

print("\nAFTER PERFORMING DOT PRODUCT:", dot_product, "\n")
print("DOT PRODUCT SHAPE:\n ", dot_product.shape) # A scalar has an empty shape
print("DOT PRODUCT CALCULATION: a[0]*b[0] + a[1]*b[1] + a[2]*b[2] = 50")
print("DOT PRODUCT CALCULATION: 1*7 + 2*8 + 3*9 = 50")

TENSOR A: tensor([1, 2, 3])
TENSOR B tensor([7, 8, 9])
TENSOR SHAPE:
 torch.Size([3])
-----------------------------------------------------------------

AFTER PERFORMING DOT PRODUCT: tensor(50) 

DOT PRODUCT SHAPE:
  torch.Size([])
DOT PRODUCT CALCULATION: a[0]*b[0] + a[1]*b[1] + a[2]*b[2] = 50
DOT PRODUCT CALCULATION: 1*7 + 2*8 + 3*9 = 50


## Broadcasting

- The automatic expansion of smaller tensors to match the shape of larger tensors during arithmetic operations.
- Broadcasting allows operations between tensors with compatible shapes, even if they don't have the exact same dimensions.

In [82]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
                 [2],
                 [3]])

print("TENSOR A:", a)
print("SHAPE:", a.shape)
print("\nTENSOR B\n\n", b)
print("\nSHAPE:", b.shape)
print("-" * 65)

# Apply broadcasting
c = a + b

print("\nTENSOR C:\n\n", c)
print("\nSHAPE:", c.shape, "\n")

TENSOR A: tensor([1, 2, 3])
SHAPE: torch.Size([3])

TENSOR B

 tensor([[1],
        [2],
        [3]])

SHAPE: torch.Size([3, 1])
-----------------------------------------------------------------

TENSOR C:

 tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

SHAPE: torch.Size([3, 3]) 



## Logical Operations

### Comparison Operators

`>, ==, <`

In [83]:
temperatures = torch.tensor([20, 35, 19, 35, 42])
print("TEMPERATURES:", temperatures)
print("-" * 50)

### Comparison Operators (>, <, ==)

# Use '>' (greater than) to find temperatures above 30
is_hot = temperatures > 30

# Use '<=' (less than or equal to) to find temperatures 20 or below
is_cool = temperatures <= 20

# Use '==' (equal to) to find temperatures exactly equal to 35
is_35_degrees = temperatures == 35

print("\nHOT (> 30 DEGREES):", is_hot)
print("COOL (<= 20 DEGREES):", is_cool)
print("EXACTLY 35 DEGREES:", is_35_degrees, "\n")

TEMPERATURES: tensor([20, 35, 19, 35, 42])
--------------------------------------------------

HOT (> 30 DEGREES): tensor([False,  True, False,  True,  True])
COOL (<= 20 DEGREES): tensor([ True, False,  True, False, False])
EXACTLY 35 DEGREES: tensor([False,  True, False,  True, False]) 



### Logical Operations

`&` for `AND`, `|` for `OR`

In [84]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
print("IS MORNING:", is_morning)
print("IS RAINING:", is_raining)
print("-" * 50)

### Logical Operators (&, |)

# Use '&' (AND) to find when it's both morning and raining
morning_and_raining = (is_morning & is_raining)

# Use '|' (OR) to find when it's either morning or raining
morning_or_raining = is_morning | is_raining

print("\nMORNING & (AND) RAINING:", morning_and_raining)
print("MORNING | (OR) RAINING:", morning_or_raining)

IS MORNING: tensor([ True, False, False,  True])
IS RAINING: tensor([False, False,  True,  True])
--------------------------------------------------

MORNING & (AND) RAINING: tensor([False, False, False,  True])
MORNING | (OR) RAINING: tensor([ True, False,  True,  True])


## Statistics

### Mean

In [85]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print("DATA:", data)
print("-" * 45)

# Calculate the mean
data_mean = data.mean()

print("\nCALCULATED MEAN:", data_mean, "\n")

DATA: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

CALCULATED MEAN: tensor(30.) 



### Standard Deviation

In [86]:
print("DATA:", data)
print("-" * 45)

# Calculate the standard deviation
data_std = data.std()

print("\nCALCULATED STD:", data_std, "\n")

DATA: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

CALCULATED STD: tensor(15.8114) 



## Data Types

In [87]:
print("DATA:", data)
print("DATA TYPE:", data.dtype)
print("-" * 45)

# Cast the tensor to a int type
int_tensor = data.int()

print("\nCASTED DATA:", int_tensor)
print("CASTED DATA TYPE", int_tensor.dtype)

DATA: tensor([10., 20., 30., 40., 50.])
DATA TYPE: torch.float32
---------------------------------------------

CASTED DATA: tensor([10, 20, 30, 40, 50], dtype=torch.int32)
CASTED DATA TYPE torch.int32


In [88]:
# Create a tensor with bfloat16 data type
bfloat_data = torch.rand(2, 3, dtype=torch.bfloat16)
print("BFloat16 Tensor:\n", bfloat_data)
print("Data type:", bfloat_data.dtype)

print("\n" + "-"*50 + "\n")

# Create a tensor with float16 data type
float16_data = torch.rand(2, 3, dtype=torch.float16)
print("Float16 Tensor:\n", float16_data)
print("Data type:", float16_data.dtype)

BFloat16 Tensor:
 tensor([[0.5117, 0.2109, 0.0469],
        [0.0352, 0.3125, 0.8867]], dtype=torch.bfloat16)
Data type: torch.bfloat16

--------------------------------------------------

Float16 Tensor:
 tensor([[0.5103, 0.6670, 0.5269],
        [0.2158, 0.2344, 0.9536]], dtype=torch.float16)
Data type: torch.float16


In [92]:
float32_tensor = torch.rand(2, 3, dtype=torch.float32)
print("Float32 Tensor:\n", float32_tensor)
print("Data type:", float32_tensor.dtype)
print("Tensor elements 0,0:\n", float32_tensor[0,0])

Float32 Tensor:
 tensor([[0.6977, 0.0494, 0.8447],
        [0.0678, 0.0891, 0.3856]])
Data type: torch.float32
Tensor elements 0,0:
 tensor(0.6977)
